
analyzer:
  strong_mode:
    implicit_casts: false

  errors:
    avoid_print: warning
    avoid_relative_lib_imports: warning
    invalid_override: warning
    invalid_override_different_default_values_named: warning
    super_goes_last: warning