name: hexagon_workspace
description: Workspace for the hexagon and hexagon_core packages.
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/hexagon_core
  - packages/hexagon
  - packages/hexagon/example
